### ISSUE TITLE
Animation not playing

### ISSUE THREAD

**Issue by jjwallace** [sonybinhle/react-expand-animated#1]
For some reason the animation doesn't play.  Is this due to CSS?

`<Expand
open={context.state.collapse}
duration={1000}
easing={'ease-in-out'}
transitions={transitions}
>`

**Comment by sonybinhle** [comment]
Could you please send me the code via CodeSandbox or other platform?
You could see the example here: https://codesandbox.io/s/107wq1klr4

**Comment by jjwallace** [comment]
I don't have the code in a snippet right now but I can set that up.
It seems to work just no animation.  Its implimented like this:
`<Expand
            open={context.state.raw}
            duration={1000}
            easing={'ease-in-out'}
            transitions={transitions}
          >
            <div className="raw-box">
              <div className="main-ui-box">
                <div className="raw-box-container">
                  <div className="main-font">RAW DATA</div>
                  <div className="raw-box-inside">
                    <ReactJson
                      src={rawData}
                      theme="summerfruit"
                      enableEdit={false}
                      enableAdd={false}
                      enableDelete={false}
                      enableClipboard={false}
                      displayDataTypes={false}
                      indentWidthN={3}
                      iconStype={'triangle'}
                    />
                  </div>
                </div>
              </div>
            </div>
          </Expand>`

**Comment by sonybinhle** [comment]
@jjwallace context.state.raw please make sure that you don't change it like: context.state.raw=true or context.state.raw=false. If context.state didn't change its reference, the children will think it is unchanged and don't update them self.
